export const characterFormScheme = {
	name: '',
	char_current_level: '1',
	char_target_level: '1', // 1,50,50A,60,60A,70,70A,80,80A,90
	basic_attack_current_level: 1,
	basic_attack_target_level: 1,
	resonance_skill_current_level: 1,
	resonance_skill_target_level: 1,
	forte_circuit_current_level: 1,
	forte_circuit_target_level: 1,
	resonance_liberation_current_level: 1,
	resonance_liberation_target_level: 1,
	intro_skill_current_level: 1,
	intro_skill_target_level: 1,
	passive_skill_1: undefined,
	passive_skill_2: undefined,
	bonus_stat_tier_1_stat_1: undefined,
	bonus_stat_tier_1_stat_2: undefined,
	bonus_stat_tier_1_stat_3: undefined,
	bonus_stat_tier_1_stat_4: undefined,
	bonus_stat_tier_2_stat_1: undefined,
	bonus_stat_tier_2_stat_2: undefined,
	bonus_stat_tier_2_stat_3: undefined,
	bonus_stat_tier_2_stat_4: undefined,
};
