# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Corepack Enable
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: PNPM Install
        run: pnpm install

      - name: Install Playwright deps
        run: pnpx playwright install-deps

      - name: Install Playwright browser
        run: pnpm exec playwright install

      - name: Run tests
        run: pnpm vitest
